name: build-deps

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 */6 * *'
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build-deps.yml"
      - "deps/Dockerfile"

jobs:
  build-deps:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert tags to lowercase
        run: |
          dockerhub_tag="${{ secrets.DOCKERHUB_USERNAME }}"
          ghcr_tag="ghcr.io/${{ github.repository_owner }}"
          echo "dockerhub_tag=${dockerhub_tag,,}" >> $GITHUB_ENV
          echo "ghcr_tag=${ghcr_tag,,}" >> $GITHUB_ENV

      - name: Build and push to Docker Hub and GHCR
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:deps"
          file: Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64, linux/s390x, linux/riscv64, linux/arm
          tags: |
            ${{ env.dockerhub_tag }}/docker-yarn-dev:deps
            ${{ env.ghcr_tag }}/docker-yarn-dev:deps
